### ISSUE TITLE
Review from DTF

### ISSUE THREAD

**Issue by skaurus** [Maclay74/steam-patch#1]
Предлагаю описать, что именно твои патчи делают :)

**Comment by Maclay74** [comment]
Hey! I believe we should continue our conversation in English as the topic at hand is quite important.

In terms of declaring the purpose of the patches, the solution is neither public nor stable at the moment. Hence, its primary role is to serve as an example and a basis for future development. Currently, it implements only one patch - fixing the TDP slider in the QAM menu, and it supports just a single device, as implied by the name of the repository.

Regarding future plans, I'm contemplating creating a database that includes various patches and supported devices. This will enable users to search for available solutions and select those that best suit their needs.

**Comment by Maclay74** [comment]
Alright, I added the list of available patches in README. I'll keep it updated down the road.
