### ISSUE TITLE
Why Rog Ally limit to 30w TDP?

### ISSUE THREAD

**Issue by fkysly** [Maclay74/steam-patch#11]
Why Rog Ally limit to 30w TDP, not 40w TDP? On windows system, turbo mode, It's limit should be 40w?

**Comment by Maclay74** [comment]
I don't think it's 40w on Windows. Is there any official statement on that matter?

**Comment by fkysly** [comment]
> I don't think it's 40w on Windows. Is there any official statement on that matter?

fine. there are a pr about suspend, u could take a look. https://github.com/Maclay74/steam-patch/pull/7
