### ISSUE TITLE
[enhancement][new feature] ROG Ally: add mapping to the back keys

### ISSUE THREAD

**Issue by ashtophet** [Maclay74/steam-patch#21]
Would it be feasible to map the separated back keys (KEY_F17 and KEY_F18) to something useful (BTN_SELECT and BTN_START, for instance) using your patching method?

TIA

The back keys on the ROG Ally show KEY_F15 in its default state (auto mode in windows). Both provide the same input and it's mean to be used as a shift key.

NeroReflex put down a kernel patch to be able to control modes[1]. In its latest incarnation, the sysfs interface can be located here[2]: 
`/sys/devices/pci0000:00/0000:00:08.1/0000:09:00.3/usb1/1-3/1-3:1.2/0003:0B05:1ABE.0004/rc71l_controller
/sys/devices/pci0000:00/0000:00:08.1/0000:09:00.3/usb1/1-3/1-3:1.0/0003:0B05:1ABE.0002/rc71l_controller
/sys/devices/pci0000:00/0000:00:08.1/0000:09:00.3/usb1/1-3/1-3:1.1/0003:0B05:1ABE.0003/rc71l_controller`
(any of them will work to control the states).

It admits three states:
0 - default one, back keys are KEY_F15: shift key, interacts with other keys.
1 - gamepad mode, back keys are separarated ordinary keys, KEY_F17 and KEY_F18.
2- lizard mode, right stick is mouse, R1 left click, R2 right click, a enter, etc. and back keys KEY_F17 and KEY_F18.

The state is remembered after sleep, even if the keys are gone and then back every other resume. So if you set it at startup it will be respected on suspend-resume).
I am using a simple systemd service that changes the mode to 1 on startup so the back keys are separate ordinary inputs[3]. In desktop I can remap them (evremap, i.e.) and use them. In gamescope it's not possible.

[1] https://github.com/NeroReflex/linux-chimeraos/blob/v6.6/linux/0002-usb-Add-a-mode-switch-for-the-controller-embedded-on.patch
[2] After the loss of N-Key device on suspend, the id changes. But it's easily scriptable: cd $(find /sys -name rc71l_controller | head -1)
[3] Really simple ones:
`cat /usr/local/bin/gamepad.sh
#!/bin/sh

cd $(find /sys -name rc71l_controller | head -1)

if test -f switch_mode
then echo 1 > switch_mode
else exit 1
fi
exit 0`
`cat /etc/systemd/system/gamepad.service
[Unit]
Description=Service that puts the Ally controller in gamepad mode
[Service]
Type=oneshot
ExecStart=/usr/local/bin/gamepad.sh
[Install]
WantedBy=multi.user.target`

**Comment by Maclay74** [comment]
Oh, I haven't heard about such an amazing progress on that field! 

The problem is, if we want to map those buttons, we need to add a virtual device that would send mocked events to useland. I'm not sure I understand the whole process correctly, but most likely it should be a separated tool, as it has nothing to do with the steam inself.

**Comment by ashtophet** [comment]
Ok, that's what I thought, thanks. 
Closing this ;)
