### ISSUE TITLE
[Rog Ally][ChimeraOS] Changing TDP does not change thermal policy

### ISSUE THREAD

**Issue by ashtophet** [Maclay74/steam-patch#4]
Steps to reproduce:

Check /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy (defaults to 0).

Change TDP to 30W.

Check /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy : it's still 0 

This issue was present too before 0.6 version.

P.S.: I don't know if it has been changed with the new BIOS (I'm using latest, 323), but this seems to not be correct in my machine:
`// Update thermal policy
        let thermal_policy = match tdp {
            val if val < 12 => 0,                 // silent
            val if (12..=25).contains(&val) => 1, // performance
            _ => 2,                               // turbo
        };`
From my testing, 0 would be balanced, 1 would be performance and 2 would be silent. Test with  a game (A plague tale innocence, high-ultra settings):
- 0 gets a TDP arround 15W (fans not very loud)
- 1 gets maximum TDP. (fans loud)
- 2 gets a TDP around 10W. (fans almost silent)

**Comment by Maclay74** [comment]
Hey, thanks for the report. 
I will check it out and get back to you with an update.

**Comment by Maclay74** [comment]
The only one thing I don't understand is the relation between TDP and thermal policy. 
Does changing thermal policy changes TDP on your device?

**Comment by ashtophet** [comment]
Yes. With BIOS 323 a change in thermal_throttle_policy has an inmediate effect on TDP here

**Comment by ashtophet** [comment]
Here is a video that shows the behaviour.
It starts a game (A plague tale innocence) with default settings. Thermal throttle policy = 0.
Then using TDP control, it ups TDP to 30W. Thermal throttle does not change.
If we change thermal throttle it changes inmediatly TDP (tested with 1,2 and 0)

https://streamable.com/t7ao1s (exires in 2 days)

**Comment by Maclay74** [comment]
I pushed a new release, can you please try 0.6.1?

**Comment by ashtophet** [comment]
Fixed! Thank you very much!
